---
# tasks file for consul-template(On Linux)
# Since Ansible 2.0, 'src' parameter of 'unarchive' module accepts external URL(ex. http://example.com/file.zip).
# But this role doesn't use this feature because zip file is always downloaded even if same file already exits in local.
# http://docs.ansible.com/ansible/unarchive_module.html
- block:
  - name: Download Consul Template archive
    get_url:
      url: "{{ consul_template_download_url }}"
      checksum: "sha256:{{ consul_template_sha256 }}"
      dest: "{{ consul_template_download_tmppath }}"
    register: dl_result
  - name: Unarchive Consul Template
    unarchive:
      src: "{{ consul_template_download_tmppath }}"
      dest: "{{ consul_template_bin_dir }}"
      copy: no
    when: dl_result.changed
  - name: Ensure execute bit of Consul Template binary
    file:
      path: "{{ consul_template_bin_dir }}/consul-template"
      mode: 'a+x'
